trigger:
- main

pool:
  name: default

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'CloudComputing_AzurePortal'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t cloudcomputingcontainer.azurecr.io/database-app:latest database-service
      docker build -t cloudcomputingcontainer.azurecr.io/gui-app:latest app-service
      docker build -t cloudcomputingcontainer.azurecr.io/metrics-app:latest metrics-service
      az acr login -n cloudcomputingcontainer
      docker push cloudcomputingcontainer.azurecr.io/database-app:latest
      docker push cloudcomputingcontainer.azurecr.io/gui-app:latest
      docker push cloudcomputingcontainer.azurecr.io/metrics-app:latest
      az aks browse --resource-group DW_CW --name iit-cloud

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'CloudComputing_AzurePortal'
    azureResourceGroup: 'CloudComputing'
    kubernetesCluster: 'CloudComputingKCluster'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'k8'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'CloudComputing_AzurePortal'
    azureContainerRegistry: 'cloudcomputingcontainer.azurecr.io'
    forceUpdate: false