trigger:
- master

pool:
  name: default

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure Portal'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t iitcloud.azurecr.io/database-app:latest database-service
      docker build -t iitcloud.azurecr.io/gui-app:latest app-service
      docker build -t iitcloud.azurecr.io/metrics-app:latest metrics-service
      az acr login -n iitcloud
      docker push iitcloud.azurecr.io/database-app:latest
      docker push iitcloud.azurecr.io/gui-app:latest
      docker push iitcloud.azurecr.io/metrics-app:latest
      az aks browse --resource-group DW_CW --name iit-cloud
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Azure Portal'
    azureResourceGroup: 'DW_CW'
    kubernetesCluster: 'iit-cloud'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'k8'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Azure Portal'
    azureContainerRegistry: 'iitcloud.azurecr.io'
    forceUpdate: false
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Azure Portal'
    azureResourceGroup: 'DW_CW'
    kubernetesCluster: 'iit-cloud'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'k8-prod'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Azure Portal'
    azureContainerRegistry: 'iitcloud.azurecr.io'
    forceUpdate: false